### ISSUE TITLE
Why not read "role-to-assume" from ~/.aws/credentials?

### ISSUE THREAD

**Issue by sir-farfan** [dcoker/awsmfa#11]
https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html
... or the ~/.aws/config file

**Comment by dcoker** [comment]
At the time awsmfa was written, the AWS SDKs and [awscli](https://pypi.org/project/awscli/) inconsistently implemented support for ~/.aws/config and ~/.aws/credentials, and did not support MFA or role assumption. The AWS config files have evolved to support these features over time. 

awsmfa does not currently support `role_arn` or `source_profile` or ~/.aws/config. If you need those features today, [awscli](https://pypi.org/project/awscli/) may be a better choice. If you have a specific use case in mind that awsmfa could solve better than awscli, please update this issue with details.

Thanks!
