### ISSUE TITLE
Does not work on windows

### ISSUE THREAD

**Issue by enderv** [dcoker/awsmfa#2]
Was trying this out and noticed it will not work on windows due to the os.rename. 

>   File "C:\Python27\lib\site-packages\awsmfa__main__.py", line 378, in update_credentials_file
>     os.rename(temp_credentials_file, filename)
> WindowsError: [Error 183] Cannot create a file when that file already exists

I can put in a PR if you'd like just let me know.

**Comment by dcoker** [comment]
Hi Enderv! Thanks for reporting this issue. I will gladly review a PR to make awsmfa work with Windows. Thanks!

**Comment by dcoker** [comment]
Fixed in #3. Thanks, enderv!

**Comment by enderv** [comment]
And thank you! This tool has been incredibly helpful!
